
//! Autogenerated weights for `xx_economics`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-11-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("xxnetwork-dev"), DB CACHE: 128

// Executed Command:
// ./xxnetwork-chain
// benchmark
// --chain=xxnetwork-dev
// --steps=50
// --repeat=20
// --pallet=xx_economics
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./weights/xx_economics.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `xx_economics`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> xx_economics::WeightInfo for WeightInfo<T> {
	// Storage: XXEconomics InflationParams (r:0 w:1)
	fn set_inflation_params() -> Weight {
		Weight::from_ref_time(14_588_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: XXEconomics InterestPoints (r:0 w:1)
	fn set_interest_points() -> Weight {
		Weight::from_ref_time(14_948_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: XXEconomics IdealLiquidityStake (r:0 w:1)
	fn set_liquidity_rewards_stake() -> Weight {
		Weight::from_ref_time(14_547_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: XXEconomics LiquidityRewards (r:0 w:1)
	fn set_liquidity_rewards_balance() -> Weight {
		Weight::from_ref_time(14_117_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}
