
//! Autogenerated weights for `xx_public`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `workstation`, CPU: `AMD Ryzen 9 5900X 12-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/xxnetwork-chain
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=xx_public
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./weights/xx_public.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `xx_public`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> xx_public::WeightInfo for WeightInfo<T> {
	/// Storage: XXSale TestnetManager (r:0 w:1)
	/// Proof Skipped: XXSale TestnetManager (max_values: Some(1), max_size: None, mode: Measured)
	fn set_testnet_manager_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_833_000 picoseconds.
		Weight::from_parts(7_033_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: XXSale SaleManager (r:0 w:1)
	/// Proof Skipped: XXSale SaleManager (max_values: Some(1), max_size: None, mode: Measured)
	fn set_sale_manager_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_682_000 picoseconds.
		Weight::from_parts(6_903_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: XXSale TestnetManager (r:1 w:0)
	/// Proof Skipped: XXSale TestnetManager (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: System Account (r:101 w:101)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Vesting Vesting (r:100 w:100)
	/// Proof: Vesting Vesting (max_values: None, max_size: Some(1057), added: 3532, mode: MaxEncodedLen)
	/// Storage: Balances Locks (r:100 w:100)
	/// Proof: Balances Locks (max_values: None, max_size: Some(1299), added: 3774, mode: MaxEncodedLen)
	/// The range of component `n` is `[1, 100]`.
	fn testnet_distribute(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `940 + n * (3 ±0)`
		//  Estimated: `7905 + n * (9914 ±0)`
		// Minimum execution time: 66_985_000 picoseconds.
		Weight::from_parts(40_828_549, 0)
			.saturating_add(Weight::from_parts(0, 7905))
			// Standard Error: 43_978
			.saturating_add(Weight::from_parts(51_607_204, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 9914).saturating_mul(n.into()))
	}
	/// Storage: XXSale SaleManager (r:1 w:0)
	/// Proof Skipped: XXSale SaleManager (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: System Account (r:101 w:101)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Vesting Vesting (r:100 w:100)
	/// Proof: Vesting Vesting (max_values: None, max_size: Some(1057), added: 3532, mode: MaxEncodedLen)
	/// Storage: Balances Locks (r:100 w:100)
	/// Proof: Balances Locks (max_values: None, max_size: Some(1299), added: 3774, mode: MaxEncodedLen)
	/// The range of component `n` is `[1, 100]`.
	fn sale_distribute(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1044 + n * (3 ±0)`
		//  Estimated: `7973 + n * (9915 ±0)`
		// Minimum execution time: 64_451_000 picoseconds.
		Weight::from_parts(34_105_465, 0)
			.saturating_add(Weight::from_parts(0, 7973))
			// Standard Error: 76_024
			.saturating_add(Weight::from_parts(52_910_182, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 9915).saturating_mul(n.into()))
	}
}
